services:
  db:
    image: postgres:15-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: /app/entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
