"""initial

Revision ID: 4061ddd51900
Revises: 
Create Date: 2025-08-12 09:32:50.781842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4061ddd51900'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('author_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('note_user_id_fkey'), 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'user', ['author_id'], ['id'])
    op.drop_column('note', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key(op.f('note_user_id_fkey'), 'note', 'user', ['user_id'], ['id'])
    op.drop_column('note', 'author_id')
    # ### end Alembic commands ###
