"""update all models to comply with sqlalchemy 2.0

Revision ID: 72ed274648de
Revises: d73865b32500
Create Date: 2025-08-26 12:56:13.131097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ed274648de'
down_revision: Union[str, Sequence[str], None] = 'd73865b32500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notecategory',
    sa.Column('note_fk', sa.Integer(), nullable=False),
    sa.Column('category_fk', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_fk'], ['category.id'], ),
    sa.ForeignKeyConstraint(['note_fk'], ['note.id'], ),
    sa.PrimaryKeyConstraint('note_fk', 'category_fk', 'id')
    )
    op.drop_table('note_category_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_category_association',
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('note_category_association_category_id_fkey')),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], name=op.f('note_category_association_note_id_fkey')),
    sa.PrimaryKeyConstraint('note_id', 'category_id', name=op.f('note_category_association_pkey'))
    )
    op.drop_table('notecategory')
    # ### end Alembic commands ###
