"""update Note to have ondelete CASCASE on author_id

Revision ID: d73865b32500
Revises: fd85ad40940b
Create Date: 2025-08-26 10:23:16.057771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73865b32500'
down_revision: Union[str, Sequence[str], None] = 'fd85ad40940b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('note_author_id_fkey'), 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'user', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key(op.f('note_author_id_fkey'), 'note', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###
